mlx_lm/utils.py

Explicitly pass the high_bits parameter in the mixed_2_6 and mixed_3_6 quant predicates instead of using default value.
Fixes [ml-explore/mlx-examples#17](https://github.com/ml-explore/mlx-lm/issues/17)
Migrated from [mlx-examples](https://github.com/ml-explore/mlx-examples/pull/1348) repo.

Update mixed_quant_predicate_builder calls to include high_bits parameter

---

mlx_lm/utils.py

For text only VLMs, so downstream users know it's not a vlm.

Remove vision config

---

mlx_lm/examples/lora_config.yaml
mlx_lm/lora.py
mlx_lm/tuner/datasets.py
mlx_lm/tuner/trainer.py
tests/test_datsets.py

- Dynamically preprocess and cache the dataset. Really speeds up cold-start time for larger datasets.
- Change padding values for speed (see benchmark)
- Seed RNG for distributed + only save weights on rank 0
Pre / post padding change:
```
Iter 100: Train loss 1.730, Learning Rate 1.000e-05, It/sec 7.039, Tokens/sec 583.184, Trained Tokens 8285, Peak mem 5.805 GB
Iter 200: Train loss 1.259, Learning Rate 1.000e-05, It/sec 7.133, Tokens/sec 573.284, Trained Tokens 16322, Peak mem 6.527 GB
```
```
Iter 100: Train loss 1.719, Learning Rate 1.000e-05, It/sec 7.244, Tokens/sec 600.669, Trained Tokens 8292, Peak mem 5.799 GB
Iter 200: Train loss 1.258, Learning Rate 1.000e-05, It/sec 8.003, Tokens/sec 644.222, Trained Tokens 16342, Peak mem 6.520 GB
```

Improvements to dataset preprocessing

---

mlx_lm/tuner/datasets.py

Instance Attribute Scope Fixing, so added missing `self` in `offset = len(tokenizer.apply_chat_template(...))`, and in `def itemlen(idx: int)`.

fix missing self references in ChatDataset class

---

mlx_lm/lora.py
tests/test_finetune.py

This PR removes the alpha parameter from the default LoRA config. I don't think it's used, per [this comment](https://github.com/ml-explore/mlx-examples/issues/982#issuecomment-2353883500):
> We don't ever explicitly compute α. The scale parameter is used directly W + scale * a @ b.T. If you wanted to work out the implied α you could multiply the scale by the lora rank you are using e.g. scale * rank.
So it's confusing to me to have it in the defaults. Particularly since the default (16) doesn't seem to match the default rank (8) and scale (10.0).
But maybe I've missed something. Feel free to close this PR if so.

Remove alpha parameter from LoRA defaults

---

mlx_lm/convert.py
mlx_lm/examples/pipeline_generate.py
mlx_lm/models/deepseek_v3.py

3 days later...
Several things in this PR
- The big fix is not using the bias shifted scores to weight the expert hidden states but using the original scores instead
- Some precision improvements to DSV3
- When dequanting from the original do it in fp32 since the scales are in fp32 and then down cast (rather than down cast the scales and then multiply). This matches how the DSV3 dequant kernel works and should give results closer to the original.
- Use the right epsilon for some RMSNorms
- Keep the expert score bias in fp32. Casting them to bf16 is quite destructive. And since this computation is done in fp32 anyway there is no perf issue. Adds a mechanism to let a model indicate which keys should not be cast.
- Fix the pipeline parallel dsv3

fix / improve dsv3

---

mlx_lm/_version.py
mlx_lm/models/plamo2.py
mlx_lm/tuner/trainer.py
tests/test_generate.py

- Use the model dtype for logits and loss to save RAM (since logsumexp accumulates in high precision this should be ok). Only cast the losses (which are much smaller) prior to the reduction.
- Use `mx.fast.rms_norm` in plamo2

Update logits to new mlx + version bump

---

mlx_lm/__main__.py
mlx_lm/cache_prompt.py
mlx_lm/chat.py
mlx_lm/fuse.py
mlx_lm/lora.py
mlx_lm/manage.py
mlx_lm/merge.py
mlx_lm/server.py

We had done the move and added the deprecation notice but the commands weren't available in `mlx_lm/__main__.py`. Added all of them and more deprecation notices.

Move from `python -m mlx_lm.generate` to `python -m mlx_lm generate`

---

mlx_lm/evaluate.py

Add distributed support to mlx_lm.evaluate.
On one machine:
```
{
"alias": "winogrande",
"acc,none": 0.6156274664561957,
"acc_stderr,none": 0.01367156760083619
}
```
On two machines:
```
{
"alias": "winogrande",
"acc,none": 0.6156274664561957,
"acc_stderr,none": 0.01367156760083619
}
```
Also cleans up the code according to the comments from the original [PR](https://github.com/ml-explore/mlx-examples/pull/1174) and fixes a few bugs:
- Add a causal mask with sequence length padding
- Fix `--no-apply-chat-template`
- Default args.limit to None. This matches `lm_eval` and before you were forced to set a limit.

Distributed Eval

---

mlx_lm/_version.py
mlx_lm/convert.py
mlx_lm/models/llama4.py
mlx_lm/utils.py
requirements.txt

Text only. Tested scout and maverick and it works well. Note when converting only the LM weights are kept so it's good to indicate that in the repo name:
```
mlx_lm.convert --hf-path meta-llama/Llama-4-Scout-17B-16E-Instruct -q --upload-repo mlx-community/Llama-4-Scout-17B-16E-Instruct-text-4bit
```
To run:
```
mlx_lm.generate --model <repo_or_path> --prompt "Write a story about Einstein" -m 2048
```
~Edit: Added a naive chunked attention so we can generate with long prompts / long generations. Doesn't yet take advantage of the fact we can trim the cache for the layers that are chunked.~
Edit: Added a custom KV cache to make the chunked attention faster.

Llama4 text only

---

mlx_lm/models/llama4.py
mlx_lm/utils.py

Remove vision_config from llama4 since it's unused, so it shouldn't be a requirement for loading a model
Also, remove vision_config from the model conversion script so that it's easier for MLX users to see if the model was converted with vision enabled

Remove vision_config from llama4 and from model conversion

---

mlx_lm/models/gpt2.py

This PR fixes two main issues in the current GPT2 implementation code that caused incorrect generation with caching. An interesting observation is the `gpt2-xl` model seems to be less dependent on positional embeddings to generate correct output; however, the smaller models tend to generate garbage with incorrect positional embeddings applied.
Specifically, the current model implementation:
1. Skips position embeddings when the input length is one (if hidden_states.shape[1] > 1:).
2. Always starts position embeddings at zero for new tokens, ignoring previously generated tokens already in the KV cache.
As a result, single‐token forward passes fail to maintain correct positions, leading to distorted or repetitive outputs.
Changes:
1.	Always Apply Position Embeddings
Removed the condition …

Fix GPT2 Incremental Generation by Correctly Applying Position Embeddings and Offsets

---

mlx_lm/models/glm4.py

This fixes the repetition from GLM4, the main reason was that the transformers and the MLX before version did not use the `partial_rotary_factor` in RoPE:
Bafore:
```text
(mlx-dev) (base)  ~/Desktop/mlx-lm/ [adding-glm4*] python -m mlx_lm.generate --model /Volumes/T7_Shield/MODELS/MLX/GLM-4-9B-0414-bf16 --prompt "Write me a function that computes fibonacci in Rust" -m 1028
<frozen runpy>:128: RuntimeWarning: 'mlx_lm.generate' found in sys.modules after import of package 'mlx_lm', but prior to execution of 'mlx_lm.generate'; this may result in unpredictable behaviour
Calling `python -m mlx_lm.generate...` directly is deprecated. Use `mlx_lm.generate...` or `python -m mlx_lm generate ...` instead.
==========
Certainly! Below is a Rust function that computes the Fibonacci sequence. The …
```

Fix GLM4 Repetition

---

mlx_lm/tokenizer_utils.py

This PR will allow mlx-vlm to use mlx-lm's tokenizer_utils directly instead of duplicating.

Patch tokenizer utils to match MLX-VLM

---

mlx_lm/cache_prompt.py
mlx_lm/models/cache.py

Closes https://github.com/ml-explore/mlx-lm/issues/103
@Blaizzy another good thing for you to use in mlx-vlm from mlx-lm are the cache routines. E.g. you'll get the bug fix here if you use them.

fix llama4 cache

---

mlx_lm/_version.py
mlx_lm/server.py

For clients which use the models endpoint of mlx-lm.server it helps to try and only find LLMs to avoid cluttering the list with useless/incompatible repo ids.

Try and scan only mlx compatible LLMs

---

mlx_lm/AWQ.md
mlx_lm/__main__.py
mlx_lm/_version.py
mlx_lm/awq.py
mlx_lm/convert.py
mlx_lm/upload.py
mlx_lm/utils.py
setup.py

Adds a command to use [AWQ](https://arxiv.org/abs/2306.00978) to quantize a model.
AWQ uses a calibration dataset to scale and clip `nn.Linear` layers, resulting in more accurate quantization. This is currently hard-coded to wiki text but should be easy to customize in the script.
Currently we support a subset of the model types in mlx-lm: Llama, Qwen and Gemma3. I prioritized the most popular according to the HF [mlx-community](https://huggingface.co/mlx-community?sort_models=downloads#models).
Since the scales and clips are fused into the previous layer, the resulting model runs at exactly the same tokens per second as the normally quantized model.
Quality benchmarks are run on 8 zero shot `lm_eval` tasks using `mlx_lm.evaluate`:
```
winogrande boolq arc_challenge arc_easy hellaswag …
```

Support AWQ Quantization

---

mlx_lm/chat.py
mlx_lm/generate.py
mlx_lm/sample_utils.py
mlx_lm/server.py
tests/test_sample_utils.py

XTC (eXclude Top Choice) is a widely used logit processor in the storytelling community in LLM, by removing the most likely tokens from consideration, thus allowing more creativity into the generations. This PR adds XTC support by adapting the text-generation-webui's implementation of the sampler creator p-e-w  to mlx_lm. 
Because it's implemented as a logit processor, it's for now only usable in mlx_lm.server, as mlx_lm.generate doesn't implement them (unless I missed something). I didn't really know if it was intended or not, so I didn't push the generate modifications I did in local.
Since it's my first real open-source contribution, it's certainly not perfect, so I'm open to any improvement suggestions !

Adding support for XTC (eXclude Top Choice) 

---

mlx_lm/generate.py
mlx_lm/sample_utils.py

Add a `--top-k` parameter to the `mlx_lm generate` CLI tool. Also, update the default `make_sampler` top-k parameter to `0`, to be consistent across the code base.

Add top-k sampling switch to the generate CLI

---

mlx_lm/server.py

Fix scan cache dir to not break on models without expected key

---

mlx_lm/evaluate.py
mlx_lm/server.py
mlx_lm/utils.py
tests/test_server.py

This fixes the overly eager prompt cache resetting where any difference in tokens causes the entire prompt cache to be re-made, which causes long delays. 
The fix finds the common prefix between the cache and the prompt and trims the cache if the common prefix is shorter than the existing cache.
Scenarios that benefit from this is when the client decides not to include a recent message in the prompt or if there are tokenizer discrepancies between the generator and the prompt. These issues commonly only affect recent (later) messages in the prompt and can more efficiently be trimmed rather than creating a new prompt cache.

Optimize prompt cache handling and add tests (Fixes #137)

---

mlx_lm/LEARNED_QUANTS.md
mlx_lm/__main__.py
mlx_lm/awq.py
mlx_lm/dwq.py
mlx_lm/lora.py
mlx_lm/models/switch_layers.py
mlx_lm/tuner/trainer.py
setup.py
tests/test_finetune.py

Relies on https://github.com/ml-explore/mlx/pull/2129
```
mlx_lm.dwq --model hf/repo
```
This learns the quantization `scales` and `biases` parameters using gradient descent and a KL loss on the unquantized model outputs. Hence "distilled" weight quantization (DWQ).
One perk of this over AWQ is it works out of the box with any model in mlx-lm and any quantized layer (embedding, swtich, linear, etc). So much more general and the code is much simpler.
Some results on Llama 3.2 1B (not all done yet)
Model | Average accuracy
------ | -------
fp16 | 47.95 
Q4 | 46.21
Q4 DWQ, 256 samples |  47.27
Q4 DWQ, 512 samples |  47.57
Q3 | 39.87
Q3 DWQ, 256 samples | 44.65
Q3 DWQ, 512 samples | 44.99
Q3 DWQ, 1024 samples | 45.14
Eval done with:
```
mlx_lm.evaluate --model mlx_model  --tasks winogrande …
```

Distilled weight quantization

---

mlx_lm/tuner/utils.py

This complete request  [#166](https://github.com/ml-explore/mlx-lm/issues/136) to be able to use Mistral3 during lora.
Without this change, mlx_vlm.lora was aborted with message "Lora does not support mistral3"

Allow to use mistral3 model type for lora

---

mlx_lm/LEARNED_QUANTS.md
mlx_lm/dwq.py
mlx_lm/tuner/trainer.py

Depends on #148 
Adds a penalty between the hidden states of the student and the teacher:
- The penalty uses L1 (L2 was too sensitive to large values).
- Defaults to use 4 layers equally spaced
- Loss is `kl_loss + activation_weight * activation_loss`
- Updates some default values which work better
New results on 2200 MMLU questions look pretty good for Gemma3 and Qwen3 4b models:

DWQ extra activation penalty

---

mlx_lm/SERVER.md
mlx_lm/server.py
tests/test_server.py

these new server.py args can be used to configure better default values for:
- num_draft_tokens
- temp
- top_p
- top_k
- min_p
- max_tokens
another arg is added to disable thinking for qwen3 models

add default params to better run quen3

---

mlx_lm/server.py

I've been fighting with an issue that my models started to hallucinate tool calls and respond in JSON strings when an empty models array was passed in the request body.
Indeed the [official API documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools) does not say what should an empty array mean. But I think logically it should mean no tools, and no tools should not behave different based on if it was indicated by a missing parameter or an empty array.
This caused me issues when I tried to use MLX-LM with an agent tool (if interested I can say, but don't want to put unsolicited ads in here), which interprets the API in away that the `tools` property is always present in the body, but if there are no tools, it is an empty array.
The problem it causes that …

Do not pass empty tools array to the tokenizer

---

mlx_lm/convert.py
mlx_lm/dwq.py
mlx_lm/utils.py
tests/test_utils.py

As title.. 
The default HF exception when the repository isn't found is fine.. I'm not sure why we catch and re-raise a custom exception.
Also in cases where you run out of disk space or the download fails for a different reason we were hiding that with the wrong model not found message.

Don't hide exception with wrong message when HF model isn't found

---

mlx_lm/generate.py
mlx_lm/models/gemma3.py
mlx_lm/models/gemma3_text.py
mlx_lm/models/qwen2.py
mlx_lm/utils.py
tests/test_generate.py

Enables `input_embeddings` to be used instead of `prompt`. This allows for prompt enrichment such as injecting image embeddings for models like Gemma3 and Qwen2/2.5VL.
I originally was only going to pipe this for Gemma3, but since `mlx-community/Qwen1.5-0.5B-Chat-4bit` (Qwen2 arch) is the current text model used for testing, I added `input_embeddings` to the Qwen2 model as well. This should eventually prove useful to be able to run Qwen2/2.5VL with image embeddings as input.
- test_generate.py test for `stream_generate` with input embeddings
- test_generate.py test for `stream_generate` with input embeddings, with `prefill_step_size` < number of embeddings
```
matt@Matts-MacBook-Pro [10:35:14] [~/Workspace/forks/mlx-lm] [input-embeddings-gemma3]
-> % python -m unittest …
```

Add input_embeddings input to generate_step, Gemma 3, Qwen 2

---

mlx_lm/server.py
tests/test_server.py

Avoid trimming the entire prompt, always leave at least one token.
Closes #182

Fix server cache

---

mlx_lm/tuner/datasets.py

Updating the error for incorrect LoRA training data to point to the correct page instead of 404.

Fix URL for LoRA Data in Error Message

---

mlx_lm/dwq.py
mlx_lm/tuner/datasets.py
mlx_lm/tuner/trainer.py

- Fix sorting for regular datasets
- Better logging for DWQ training
- Tune parameters to improve performance (TODO share some results)
Perplexity for Qwen3 0.6B Base
Model | Perplexity
----- | ------
Base model | 9.97
Q4 32 | 11.92 |
Q4 64 | 12.58 |
Q4 32 DWQ original | 11.37
Q4 64 DWQ original | 11.91
Q4 32 DWQ new | 10.87
Q4 64 DWQ new | 11.24
The new DWQ also includes training on more samples. I didn't put all the changes here.. but most of the updates led to incremental improvements.
As you can see the perplexity is still not matched to the base model. Training longer helps but it's diminishing returns. The benchmark here is particularly diverse and high ppl.. on other benchmarks the gap from DWQ to the full precision model can be quite a bit smaller.

DWQ updates

---

mlx_lm/models/mistral3.py

This PR extends @mattjcly's PR #181 to optionally pipe `input_embeddings` through the `mistral3` model to the underlying `llama` model. This enables sending image embeddings to mistral3 as discussed in our [blog post](https://lmstudio.ai/blog/unified-mlx-engine).

Pipe input_embeddings through mistral3 model_type

---

mlx_lm/tokenizer_utils.py

Fixed an IndexError that occurs in the `NaiveStreamingDetokenizer` class's `text` property when trying to access the last character of an empty string. Added a length check before accessing `self._current_text[-1]`.
When the tokenizer tries to clean up tokenization spaces, it attempts to check if the current text ends with a space without first verifying that there is any text to check. This causes an IndexError when `self._current_text` is empty.
Added a length check `len(self._current_text) > 0` before attempting to access the last character.

Fix `IndexError` in `NaiveStreamingDetokenizer`

---

mlx_lm/models/bitlinear_layers.py
mlx_lm/models/bitnet.py
mlx_lm/utils.py

Follow up PR to: #219 - this is an alternative approach to support llama-compatible bitnet models such as Falcon-E or Falcon3-1.58bit series. 
The trick is to check inside the config if the attribute `quantization_config` exists, and check if the bitnet class used is the old (without norm and with invert scales), or the new one (with norm and without invert weight scales)
Confirmed that both Falcon-E and Microsoft bitnet works with this PR
@awni @Blaizzy @angeloskath

Feat: add falcon-e support for bitnet models

---

mlx_lm/utils.py

A recent commit ([e8c2cfce](https://github.com/ml-explore/mlx-lm/commit/e8c2cfce6a3c039136c14fdfe9a5a279a811db56)) introduced a new requirement that a `README.md` must be present to load a model. This PR modifies `get_model_path` to return `None` for hf_path if the model card is not present in the local model path.

Allow generation without README

---

mlx_lm/generate.py
tests/test_generate.py

The [mlx-engine](https://github.com/lmstudio-ai/mlx-engine) [unified architecture](https://lmstudio.ai/blog/unified-mlx-engine) uses mlx-vlm to compute token and image embeddings, then passes those to mlx-lm for generation. Currently, "unified" models only pass those embeddings and not the input token IDs.
The Gemma3n implementation requires token IDs even when passing input embeddings directly, as they are needed to compute the Per Layer Embeddings.
This PR modifies the `generate_step` function to allow for just `prompt`, just `input_embeddings`, or both as input. These are then piped through to the underlying model calls. None of this is specific to Gemma3n, so it can be re-used by other models that require the same inputs.

Allow prompt and input_embeddings

---

mlx_lm/models/switch_layers.py
mlx_lm/quant/dwq.py
mlx_lm/quant/dynamic_quant.py
mlx_lm/tuner/losses.py

This uses https://github.com/ml-explore/mlx/pull/2335 to train MoE DWQs and also adds a custom metal kernel for the KL loss which speeds it up a bit (it depends on how big of a fraction of the total cost it was) and saves quite a bit of memory especially for models with large vocabularies.
Dynamic quant for `Qwen3-0.6B-Base`
```
Before:                   43s and 17.9GB
After:                    40s and 11.4GB
After with checkpointing: 47s and 9GB
```
Dynamic quant for `Qwen3-8B`
```
Before:                   7m 37s and 91.6GB
After:                    7m 27s and 88.2GB
After with checkpointing: 8m 40s and 74.6GB
```
For DWQ we can now train properly the switch layers and with gradient checkpointing and the kl-loss we can use larger batch size so we get better utilization of the batch …

KL loss and memory improvements for DWQ and dynamic quant

---

mlx_lm/tuner/trainer.py
tests/test_tuner_trainer.py

Simple typo that results in all workers loading the same data.

Fix ddp workers loading the same data

---

mlx_lm/generate.py

This PR allows the following `generate_step` parameter combinations. Currently only 1 and 3 are allowed.
1. `len(prompt) > 0 and input_embeddings is None` i.e. prompt only
2. `len(prompt) == 0 and input_embeddings is not None` i.e. input embeddings only
3. `input_embeddings is not None and len(prompt) == len(input_embeddings)` i.e. sequence lengths match
This still provides a helpful check that sequence lengths match when both are provided, but allows for just `input_embeddings` to be provided when the underlying model implementation only requires one or the other.

Allow empty prompt with input_embeddings

---

mlx_lm/tuner/callbacks.py

Ensures all metrics are JSON-serializable by converting MX arrays before logging to wandb.
Avoids TypeError: Object of type array is not JSON serializable.

Update W&B logging crash in MLX-LM-LORA

---

mlx_lm/LEARNED_QUANTS.md
mlx_lm/LORA.md
mlx_lm/_version.py
mlx_lm/generate.py
mlx_lm/quant/dwq.py
mlx_lm/tuner/trainer.py
setup.py

Pretty fast on an A100:
```
mlx_lm.lora --model meta-llama/Llama-3.2-3B-Instruct --data mlx-community/WikiSQL --train --iters 100
Loading pretrained model
Fetching 11 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 101848.44it/s]
Loading datasets
Loading Hugging Face dataset mlx-community/WikiSQL.
Training
Trainable parameters: 0.041% (1.311M/3212.750M)
Starting training..., iters: 100
Calculating loss...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:05<00:00,  4.75it/s]
Iter 1: Val loss 2.936, Val took 5.265s
Iter 10: Train loss 2.662, Learning Rate 1.000e-05, It/sec 0.490, Tokens/sec 161.374, Trained Tokens 3290, Peak mem 9.707 GB …
```

Lora works with cuda backend

---

mlx_lm/_version.py
mlx_lm/models/gemma3n.py

Closes #322
When `cache=None`, Gemma-3n models produced incorrect outputs due to shared KV layers expecting initialized `Cache` objects but receiving `None` values.
This change ensures proper cache initialization even when no cache is provided by the user, fixing a critical inference bug that caused 27+ logit differences between cached and uncached forward passes.
```diff
- cache = [None] * len(self.layers)
+ cache = self.make_cache()
```
Sample output, when running the same script as in #322:
```
Logits without cache - yes: 16.125, no: 8.0
Logprobs without cache - yes: 0.0, no: -8.125
Probabilities without cache - yes: 1.0, no: 0.0002960447163786739
Logits with cache - yes: 15.25, no: 7.625
Logprobs with cache - yes: 0.0, no: -7.625
Probabilities with cache - yes: 1.0, no: …
```

Initialize empty cache when cache=None for Gemma‑3n models

---

mlx_lm/evaluate.py
setup.py
tests/test_evaluate.py

- Fix NameError in `loglikelihood_rolling` method where undefined `texts` variable was referenced instead of `inputs`
- Add comprehensive tests to prevent regression
The `loglikelihood_rolling` method in `mlx_lm/evaluate.py` was referencing an undefined `texts` variable in the batch processing loop (lines 279-280), when it should have been using the `inputs` variable that was created from tokenizing the requests on line 277.
This would cause a `NameError: name 'texts' is not defined` when the method was called.
- Fixed variable reference from `texts` to `inputs` in the batch loop
- Added `tests/test_evaluate.py` with comprehensive tests that verify:
- The bug fix works correctly 
- Proper batching behavior
- The test fails when the bug is present (regression protection)

Fix NameError in loglikelihood_rolling method

---

mlx_lm/evaluate.py

This closes #347 
To test it:
```bash
export HF_ALLOW_CODE_EVAL="1"
mlx_lm.evaluate --model mlx-community/Qwen3-Coder-30B-A3B-Instruct-4bit-DWQ --tasks humaneval_instruct --max-tokens 5000 --no-apply-chat-template --confirm-run-unsafe-code`
```

feat: add --confirm-run-unsafe-code CLI option to allow execution of untrusted code

---

mlx_lm/models/gpt_oss.py

This PR changes the GPT OSS implementation such that it routes to the fused sdpa.
The idea is quite simple but adds a tiny bit of annoying book keeping. Instead of adding sinks to the softmax and dropping it after the softmax we add an extra key and value that is 0 and add the sinks as bias towards these keys and values. That means that we have an additive float mask that is not quite triangular but has a specific value for the first index.
This implementation also keeps the last mask in `_previous_mask` so that we don't have to recreate it every time which does make a difference in speed.
Some numbers:
```
Generate 2k tokens
main:                 61.9 tps
sdpa (no mask cache): 66.5 tps
sdpa:                 68.8 tps
Generate 1k tokens starting from 15k
main:                 39.8 tps
sdpa …
```

Route the gpt_oss to fused sdpa

---

mlx_lm/models/gpt_oss.py
mlx_lm/tuner/utils.py
tests/test_models.py

This PR adds additional feature support for the GPT-OSS model in MLX-LM. GPT-OSS is a new model from OpenAI featuring Mixture of Experts (MoE) with alternating attention patterns.
This PR is totally optional for `mlx-lm` as I need these features for my other project. Feel free to decline if it's not relevant to MLX LM. 
- **Mixture of Experts**: 128 local experts with 4 experts per token
- **Alternating Attention**: Layers alternate between sliding window and full attention
- **YARN RoPE Scaling**: Advanced positional encoding support
- **SwiGLU Activation**: Custom activation with proper dtype preservation
- **LoRA Support**: Compatible with MLX-LM's fine-tuning framework
- **Fixed parameter naming**: Changed `num_experts_per_tok` to `experts_per_token` to match config
- **Added …

Add Additional Features of  GPT-OSS Model : Lora, Alternating attention, MoE Support

---

mlx_lm/lora.py

to get rid of this when training:
```text
....
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.
Do you wish to run the custom code? [y/N] y
```

Adding trust_remote_code=True for training

---

mlx_lm/lora.py

Before:
```text
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/gokdenizgulmez/Desktop/mlx-lm/mlx_lm/lora.py", line 381, in <module>
main()
File "/Users/gokdenizgulmez/Desktop/mlx-lm/mlx_lm/lora.py", line 357, in main
args = parser.parse_args()
^^^^^^^^^^^^^^^^^^^
File "/opt/miniconda3/lib/python3.12/argparse.py", line 1904, in parse_args
args, argv = self.parse_known_args(args, namespace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/miniconda3/lib/python3.12/argparse.py", line 1914, in parse_known_args
return self._parse_known_args2(args, namespace, intermixed=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/miniconda3/lib/python3.12/argparse.py", line …
```

remove comma and add muon

---

mlx_lm/_version.py
mlx_lm/models/qwen2_vl.py
mlx_lm/models/rope_utils.py
mlx_lm/utils.py

Adds the [Qwen2-VL](https://huggingface.co/collections/Qwen/qwen2-vl-66cee7455501d7126940800d) model family for text-only inference. Sibling of [lmstudio-ai/mlx-engine#215](https://github.com/lmstudio-ai/mlx-engine/pull/215).
Because Qwen2-VL and Qwen2.5-VL have the same language model implementation, the [Qwen2.5-VL](https://huggingface.co/collections/Qwen/qwen25-vl-6795ffac22b334a837c0f9a5) model family is supported and mapped to `qwen2_vl`.

Add Qwen2-VL model implementation

---

mlx_lm/__main__.py
mlx_lm/perplexity.py
setup.py

Adds a utility, `mlx_lm.perplexity`, for computing perplexity over the same dataset used in `quant/dynamic_quant.py`. Adds standard errors for perplexity comparisons. Properly implements a [gist](https://gist.github.com/N8python/fe048698e17fc430416d28d4689603dc) that people reported was useful.
```
usage: mlx_lm.perplexity [-h] --model MODEL [--batch-size BATCH_SIZE] [--sequence-length SEQUENCE_LENGTH] [--num-samples NUM_SAMPLES] [--seed SEED]
Evaluate perplexity of MLX models
options:
-h, --help            show this help message and exit
--model MODEL         Path to model or Hugging Face model ID
--batch-size BATCH_SIZE
Batch size for evaluation
--sequence-length SEQUENCE_LENGTH
Sequence length for evaluation
--num-samples NUM_SAMPLES
Number of samples to use (-1 for all available) …
```

Add `mlx_lm.perplexity`

---

mlx_lm/__main__.py
mlx_lm/benchmark.py
setup.py

Add `mlx_lm.benchmark` to make it easy to do prompt / generation timings.
For example:
```
mlx_lm.benchmark -p 2048 -g 128 
```
Outputs:
```
Running warmup..
Timing with prompt_tokens=2048 and generation_tokens=128.
Trial 1:  prompt_tps=2902.212, generation_tps=205.325, peak_memory=3.285
Trial 2:  prompt_tps=2901.392, generation_tps=205.243, peak_memory=3.285
Trial 3:  prompt_tps=2902.077, generation_tps=205.256, peak_memory=3.285
Trial 4:  prompt_tps=2902.258, generation_tps=204.587, peak_memory=3.286
Trial 5:  prompt_tps=2902.890, generation_tps=205.085, peak_memory=3.286
Averages: prompt_tps=2902.166, generation_tps=205.099, peak_memory=3.285
```

Benchmark script

---

mlx_lm/server.py

If you interrupt the connection to the server during generation a `BrokenPipeError` is raised which is not caught or handled. Due to the current code, `self.prompt_cache.cache` will have been updated (it gets updated with each token in `stream_generate`), but `self.prompt_cache.tokens` will not be updated. This PR changes the code to append the token to the `PromptCache` object earlier to mitigate the issue.
There is still a possibility that the `self.prompt_cache.cache` is corrupted with this fix, but the chance is minimized. Fixing the issue fully would likely require catching the exception, verifying that `self.prompt_cache.cache` is in a consistent state, then appending the tokens. I figured this was a reasonable initial fix for the issue. Maybe a follow-up PR can fix this more fully.

Fix prompt cache corruption when generation is interrupted

---

mlx_lm/perplexity.py

As per: https://x.com/kernelpool/status/1961640338214588625
Numpy random seed was not set, multiple runs were not deterministic.

Fix mlx_lm.perplexity seed w/ np.random.seed to ensure determinism across runs

---

mlx_lm/models/nemotron_h.py

Fixes:
```text
ValueError: Expected shape (4480, 4480) but received shape (5120, 4480) for parameter backbone.layers.14.mixer.q_proj.weight
```
by adding attention head dim in model args

Fix Nemotron H loading error

---

mlx_lm/models/granitemoehybrid.py
mlx_lm/models/ssm.py
tests/test_models.py

Adds a custom SSM kernel + some optimizations to SSM.
Since these are more common.. I think it's worth having a common + fast implementation that hybrid SSM models can use.
TODO:
- Use ssm step for other models where possible
- Possible speed up prompt processing using scan formulation instead of recurrent formulation.

Faster ssm

---

mlx_lm/models/qwen3_next.py

the gating is not being applied in the `recurrent_gated_delta_rule`, baking the state would just keep accumulating without any forgetting mechanism, which would break the recurrent dynamics.

fix qwen3 next

---

mlx_lm/models/mistral3.py
mlx_lm/models/qwen2_vl.py

This PR fixes `TypeError: Model.__call__() got an unexpected keyword argument 'mask'`.
After recent changes, the underlying language models for `qwen2_vl` and `mistral3` do not accept `mask` as an argument.

Fix `TypeError: Model.__call__() got an unexpected keyword argument 'mask'` for qwen2_vl, mistral3

---

mlx_lm/generate.py
mlx_lm/models/cache.py
mlx_lm/models/gemma3_text.py
tests/test_generate.py
tests/test_models.py
tests/test_prompt_cache.py

Makes a `BatchRotatingKVCache` which is very similar to `RotatingKVCache` but supports left-padded batches.
Results on a 750 question subset of MMLU are close. Single is slightly better.. I am not sure if it's enough to be concerned. I will try some other models and see.
```
mlx_lm.evaluate --task mmlu_pro --limit 50 --model google/gemma-3-4b-it --max-tokens 8192
```
Single: 39.57 
Batch: 39.14
Also this will require https://github.com/ml-explore/mlx/pull/2608

Add batch support for sliding window cache

---

mlx_lm/models/deepseek_v2.py
mlx_lm/models/deepseek_v3.py
requirements.txt

Fixed pipeline parallel prompt processing. Requires https://github.com/ml-explore/mlx/pull/2606
This works now:
```
mlx.launch --hostfile hosts.json mlx-lm/mlx_lm/examples/pipeline_generate.py --model mlx-community/DeepSeek-Coder-V2-Lite-Instruct-4bit
```

Use depends in pipeline parallel

---

mlx_lm/lora.py
mlx_lm/tuner/utils.py
tests/test_finetune.py

This changes the default behavior to apply lora to all layers which it can be used on. But it's much simpler / more scalable. If one needs flexibility then you can use the config.

Simplify to_lora to not hardcode model types

---

mlx_lm/convert.py

Please review this pull request with skepticism. It is intended as a question, "Is the current behavior intended, and if not should it be this instead?" accompanied by code.
Currently:
```python
def mixed_quant_predicate(
path: str,
module: nn.Module,
) -> Union[bool, dict]:
"""Implements mixed quantization predicates with similar choices to, for example, llama.cpp's Q4_K_M.
Ref: https://github.com/ggerganov/llama.cpp/blob/917786f43d0f29b7c77a0c56767c0fa4df68b1c5/src/llama.cpp#L5265
By Alex Barron: https://gist.github.com/barronalex/84addb8078be21969f1690c1454855f3
"""
index = (
int(path.split(".")[layer_location])
if len(path.split(".")) > layer_location
else 0
)
use_more_bits = (
index < num_layers // 8
or index >= 7 * num_layers // 8
or (index - num_layers // 8) % 3 == 2
)
if "v_proj" …
```

Make mixed quantization affect attention in DeepSeek V3, others

---

mlx_lm/_version.py
mlx_lm/models/granitemoehybrid.py

This PR extends the `granitemoehybrid.py` model implementation to support "degenerate" cases of the architecture where a dense block is used in place of an MoE and/or all layers are attention layers (non-hybrid). There will be some models in the granite 4 family that require these cases.
In order to get _any_ of these models to run locally on this branch, I also had to remove [this line](https://github.com/ml-explore/mlx-lm/blob/main/mlx_lm/models/base.py#L136). The version of `mlx` I have (installed with `pip install -e` from the tip of `main` / `bbf14239`) does not seem to support the `sinks` argument, though I do see it implemented [here](https://github.com/ml-explore/mlx/blob/bbf14239538c18a9f8a3d61f52ab0f29589410f0/python/src/fast.cpp#L237), so it's possible that something didn't get …

feat: Refactor granitemoehybrid to support dense and non-hybrid variants

---

mlx_lm/models/qwen3_next.py

Fixes Python 3.8/3.9 compatibility issue in `qwen3_next.py`.
- `qwen3_next.py` uses `|` union syntax (line 60: `mx.array | None`)
- This syntax requires Python 3.10+ or `from __future__ import annotations`
- Package declares `python_requires>=3.8` but breaks on Python 3.9
- Affects macOS system Python (3.9.6, shipped with macOS 15 Sequoia)
Missing `from __future__ import annotations` import at top of file.
Add the missing import (2 lines: import + blank line before copyright).
Verified on Python 3.9.6 (macOS 15.6.1):
```python
from mlx_lm.utils import _get_classes
config = {"model_type": "qwen3_next"}
model_class, args_class = _get_classes(config)
```
Other model files (e.g., `llama.py`) use `Optional[...]` syntax for Python 3.8+ compatibility. This fix brings `qwen3_next.py` in line with …

Fix: Add __future__ annotations import to qwen3_next.py for Python 3.9 compatibility

---

mlx_lm/models/deepseek_v32.py

The following fixes/changes are included in this PR
- Added missing ReLU activation (`mx.maximum(scores, 0)`) in indexer after computing attention scores, as implemented by reference [kernel.py:241](https://github.com/deepseek-ai/DeepSeek-V3.2-Exp/blob/main/inference/kernel.py#L241) to filter out negative attention scores before token selection.
- Changed `scaled_dot_product_attention(..., cache=cache)` to `cache=cache[0]` to pass `KVCache` object instead of `CacheList` wrapper
- Added `scores.sum(axis=1)` in indexer to aggregate per-head scores into unified token selection (matching [kernel.py:244](https://github.com/deepseek-ai/DeepSeek-V3.2-Exp/blob/main/inference/kernel.py#L244)), changing output shape from `(B, heads, L, topk)` to `(B, L, topk)` and fixing repetitive generation …

Fix sparse token selection in deepseek v3.2
