ml-explore/mlx-lm

mlx_lm/models/gemma3.py, mlx_lm/models/gemma3_text.py
Add text only support for the new gemma3 models (closes #19)
```
mlx_lm.convert --hf-path mlx-community/gemma-3-4b-it-bf16 --dtype bfloat16 --upload-repo mlx-community/gemma-3-text-4b-it-4bit
```
```
mlx_lm.generate --model  mlx_model --prompt "Write a story about Einstein" -m 256
==========
The rain in Zurich was a persistent, grey drizzle, clinging to the cobblestones and blurring the gaslights into hazy halos. Albert Einstein, a young patent clerk with a wild shock of hair and a mind that seemed to operate on a different frequency, was staring out the window of his cramped office. He wasn't processing the paperwork, not really. He was lost in a universe of his own making, a universe where time wasn't a river, but a fabric, and space wasn't empty, but a stage upon which everything …
```
=> gemma3 text only support

mlx_lm/models/deepseek_v3.py
Since we can load fp8, allow dequantization in mlx-lm directly to simplify creating new quants of dsv3.
=> dequantize dsv3

mlx_lm/models/qwen2.py, mlx_lm/models/rope_utils.py, tests/test_models.py
As title. Closes https://github.com/ml-explore/mlx-lm/issues/5
=> Add yarn option for qwen2

mlx_lm/models/cohere2.py
=> Fix cohere2

mlx_lm/models/gemma2.py
Closes https://github.com/ml-explore/mlx-lm/issues/18
=> fix mask for gemma2

mlx_lm/server.py
Previously we only used the prompt cache for multi-turn conversation. This also uses the cache for multiple queries on the same long prompt.
=> Use the prompt cache for completions in server

mlx_lm/_version.py, mlx_lm/tuner/utils.py, mlx_lm/utils.py
- Fix model tags for upload
- Allow fine-tuning for gemma3
=> Fix tags and allow fine-tuning of gemma3

ACKNOWLEDGMENTS.md
Just removed the second '-' and 'added' to 'Added'
=> Fix acknowledgments typo

mlx_lm/models/cohere2.py, mlx_lm/models/gemma3_text.py
=> Fix gemma3 and cohere2 sliding window

mlx_lm/_version.py, mlx_lm/models/base.py, mlx_lm/models/cohere2.py, mlx_lm/models/gemma2.py, mlx_lm/models/gemma3.py, mlx_lm/models/gemma3_text.py, mlx_lm/models/phi3small.py, mlx_lm/utils.py, requirements.txt, setup.py, tests/test_prompt_cache.py
Pre/Post for 4-bit Mistral 7B on M2 Utra
Prompt: 33898 tokens, 676.212 tokens-per-sec
Peak memory: 12.257 GB
Prompt: 33898 tokens, 869.279 tokens-per-sec
Peak memory: 9.111 GB
=> Updates for causal mask

mlx_lm/server.py
This PR will fix https://github.com/ml-explore/mlx-lm/issues/15
IPv6 server will help self-hosting users in countries where IPv4 addresses are insufficient but IPv6 addresses are abundant.
=> Add support for IPv6 server

mlx_lm/evaluate.py, mlx_lm/generate.py, mlx_lm/server.py, mlx_lm/tuner/trainer.py, requirements.txt
=> Remove metal in memory APIs

mlx_lm/models/switch_layers.py
First of hopefully a few that will increase MoE prompt processing speed. This is extremely simple and it comes with modest speedups but across the board so I think it is worth merging as a first step.
Some speed measurements:
| Model | Prompt | Before | After | Speedup |
| --- | --- | --- | --- | --- |
| DeepSeek-v3-0324 @ 4bit | ~1100 tokens | 78 tps | 112 tps | 43% |
| Mixtral-8x7B @ 4bit | ~1300 tokens | 174 tps | 192 tps | 10% |
| DeepSeek-V2-Lite-Chat @ 4bit | ~1200 tokens | 883 tps | 1033 tops | 17% |
| Qwen1.5-MoE-A2.7B @ 4bit | ~1200 tokens | 1200 tps | 1400 tps | 17% |
=> Ensure the gather_mm is in order

mlx_lm/LORA.md, mlx_lm/tuner/datasets.py
Update dataset configuration in LORA.md and enhance ConcatenatedDataset to avoid AttributeError: 'ConcatenatedDataset' object has no attribute 'process'.
Closes #59
=> ConcatenatedDataset error fix

mlx_lm/models/deepseek_v2.py
=> Fix DeepSeek V2 pipeline parallel

mlx_lm/models/nemotron-nas.py
Adding support for nemotron-nas such as
> nvidia/Llama-3_1-Nemotron-Ultra-253B-v1
> nvidia/Llama-3_3-Nemotron-Super-49B-v1
[Paper](https://arxiv.org/abs/2411.19146)
=> Support nemotron-nas

mlx_lm/models/kimi_vl.py
Add text-only version of Kimi VL (~2B active MoE).
```
mlx_lm.convert --hf-path moonshotai/Kimi-VL-A3B-Thinking -q --upload-repo mlx-community/Kimi-VL-A3B-Thinking-4bit
```
```
mlx_lm.generate --model mlx_model --prompt "Write a story about Einstein" -m 4096
```
```
...
---
**Themes**: Curiosity, perseverance, and the human spirit’s capacity to challenge the unknown.  
**Style**: A blend of historical narrative and poetic reflection, capturing Einstein’s essence as both a revolutionary and a man of profound humanity.<|im_end|>
==========
Prompt: 21 tokens, 14.296 tokens-per-sec
Generation: 1394 tokens, 116.925 tokens-per-sec
Peak memory: 9.441 GB
```
=> kimi_vl text only

mlx_lm/models/gemma3_text.py
Thanks @Blaizzy for pointing out the fix for fp16.
=> fix gemma3 in fp16

mlx_lm/SERVER.md, mlx_lm/server.py, tests/test_server.py
Alternate of https://github.com/ml-explore/mlx-lm/pull/62 with some modifications.
=> Server draft

mlx_lm/AWQ.md, mlx_lm/awq.py, setup.py
Default options included to clarify that 3bit quantization is deafult.
=> Update AWQ docs to include default values

mlx_lm/convert.py
When converting models, if the `dtype` argument is unspecified, load the weights as specified in the config.json `torch_dtype`. If `torch_dtype` key is not found or the value is unrecognized, fallback to the model weights' dtype. The conversion CLI will still respect the user's `--dtype` argument if they wish to override this behavior
=> During model conversion, default dtype to config.json torch_dtype

mlx_lm/models/base.py, mlx_lm/models/gemma3_text.py, tests/test_models.py
=> fix quant sdpa and gemma3

mlx_lm/awq.py, mlx_lm/models/qwen3_moe.py
closes #133 
Also adds qwen3 config for AWQ.
=> Fix Qwen3 MoE fine-tunig

mlx_lm/AWQ.md
Added seed to evaluate command and fixed upload parameters.
=> Update AWQ evaluate and upload

mlx_lm/models/mimo.py, mlx_lm/tuner/utils.py
Huggingface: https://huggingface.co/XiaomiMiMo
Github: https://github.com/XiaomiMiMo/MiMo @XiaomiMiMo
=> :sparkles: feat: Add support for Xiaomi MiMo model

mlx_lm/convert.py
This PR adds Mixed-3-4bit quant.
=> Add mixed-3-4bit quant

mlx_lm/lora.py, mlx_lm/tuner/trainer.py
Closes https://github.com/ml-explore/mlx-lm/issues/150
=> Fix lora test

mlx_lm/awq.py
- Use the suggested defaults as in #149
- Matches the standard AWQ clipping implementation (use a single clip value)
- Adds a fallback to the original weights for a given block if the loss is nor reduced
=> improvements / defaults for awq

mlx_lm/LORA.md
=> Update LORA.md for wikisql

mlx_lm/models/llama.py, mlx_lm/models/pixtral.py
Pipes Pixtral model (i.e., https://huggingface.co/mlx-community/pixtral-12b-4bit) to underlying llama model arch
Demo:
```
/Users/matt/Workspace/forks/mlx-lm/.venv/bin/python -m mlx_lm.generate --model /Users/matt/.cache/lm-studio/models/mlx-community/pixtral-12b-4bit --prompt <s>[INST]Compute the square root of 32[/INST] --max-tokens 500 --temp 0
==========
To compute the square root of 32, you can use the following steps:
1. **Prime Factorization**:
- Find the prime factors of 32.
- \( 32 = 2 \times 2 \times 2 \times 2 \times 2 \)
- This can be written as \( 32 = 2^5 \).
2. **Square Root Calculation**:
- The square root of a number is a value that, when multiplied by itself, gives the original number.
- For \( 32 = 2^5 \), the square root is \( 2^{5/2} \).
3. **Simplify the …
```
=> Pixtral text support, pipe input_embeddings through llama arch

mlx_lm/examples/lora_config.yaml
changed `'wandb-project"` to `"wandb-project"`
=> fix WandB setting in lora_congig.yaml

mlx_lm/sample_utils.py
```
mlx_lm.generate --model mlx-community/Qwen3-1.7B-4bit --prompt "Write a story about Einstein" -m 512 --top-p 0.95 --temp 0.6 --seed 1
```
Pre: 283.09 tok/s
Post: 291.67 tok/s
=> Faster top-p and min-p sampling

mlx_lm/lora.py, mlx_lm/tuner/trainer.py
Adding a tqdm progress bar for evaluate to make it more transparent what’s happening when --test is called, rather than an empty screen.
=> Add Evaluation Progress

mlx_lm/_version.py, setup.py
=> Fix quant package

mlx_lm/_version.py, mlx_lm/quant/dynamic_quant.py
Fix dynamic quantization for linear layers with biases.
=> fix dynamic quant for bias

mlx_lm/models/cache.py, mlx_lm/models/deepseek_v3.py, mlx_lm/models/kimi_vl.py
=> Fx cast predicate

mlx_lm/models/dbrx.py, mlx_lm/models/deepseek.py, mlx_lm/models/deepseek_v3.py, mlx_lm/models/phi.py, tests/test_models.py
=> Allow models to be pickled + test

mlx_lm/_version.py, mlx_lm/convert.py, mlx_lm/models/gemma3n.py
Adds Gemma 3n with text-only model support.
```
mlx_lm.generate --model google/gemma-3n-E2B-it --prompt "Write a story about Einstein" -m 128
```
Closes #257
=> Gemma3n text only support

mlx_lm/convert.py, mlx_lm/fuse.py, mlx_lm/quant/awq.py, mlx_lm/quant/dwq.py, mlx_lm/quant/dynamic_quant.py, mlx_lm/tuner/utils.py, mlx_lm/utils.py, tests/test_utils_load_model.py
Before it was broken to do:
```bash
mlx_lm.convert --hf-path my/local/path -q
```
=> Allow converting local models

mlx_lm/LEARNED_QUANTS.md, mlx_lm/__main__.py, mlx_lm/evaluate.py, mlx_lm/quant/gptq.py, mlx_lm/utils.py, setup.py
Results comparing different methods for Qwen3 0.6B base:
Model | BPW | PPL
--- | --- | ---
BF16 | 16.0 | 9.967
Q4, 32 | 5.0 | 11.916
GPTQ | 5.02 | 11.405
Dynamic | 5.0 | 11.25
DWQ | 5.0 | 10.87
Gemma3 1B PT
Model  |  BPW | PPL
--------- | ----- | -----
BF16 | 16.0 | 22.558
Q4, 32 | 5.0 | 25.91
Dynamic | 5.0 | 24.533
GPTQ | 4.965 | 25.234
DWQ | 5.0 | 23.104
=> GPTQ quantization

mlx_lm/models/hunyuan.py
Reduction in MoE layer should be done in higher precision.
=> fix hunyuan

mlx_lm/quant/dwq.py
=> feat: DWQ for Hunyuan-A13B-Instruct and trust_remote_code argument

mlx_lm/models/exaone4.py, mlx_lm/tuner/utils.py
```bash
mlx_lm.generate --model mlx_model --prompt "Write a story about Einstein" -m 1024                     
==========
**Title: *The Relativity of Time***  
In the quiet town of Princeton, New Jersey, Albert Einstein sat by his study window, staring at the swirling leaves of an old oak tree. At 86 years old, his hair was white, his hands trembling slightly, but his mind remained as sharp as ever.  
One evening, a young physicist named Clara knocked on his door. She had read all his papers, solved many of his equations, but she still didn’t understand the true nature of time.  
“Professor Einstein,” she said, “they say you once said time is an illusion. But if time doesn’t exist, how do we measure our lives?”  
Einstein chuckled. “Time is not an illusion, my dear Clara. It is a …
```
=> add exaone4

mlx_lm/server.py
=> add v1/models/repo_id

mlx_lm/models/gemma3n.py
fix the gemma3n due to the config changes -> https://huggingface.co/google/gemma-3n-E4B-it/commit/72639b6c011b3d1357b0777871e0cfba6cac5b04
=> chore: fix gemma3n intermediate_size config

mlx_lm/models/glm4_moe.py, mlx_lm/quant/dwq.py
Updated GLM-4 MoE model implementation to support DWQ quantization method
=> Changed GLM-4 MoE support for DWQ quantization

mlx_lm/quant/dwq.py
This adds a persistent validation set for DWQ training so we can be more certain the model is making / made progress.
It also prints a big warning if the final validation loss is not better than the initial validation loss.
=> Add validation set for DWQ

mlx_lm/_version.py, mlx_lm/models/deepseek_v3.py, mlx_lm/models/gpt_oss.py, mlx_lm/models/rope_utils.py, mlx_lm/models/switch_layers.py, mlx_lm/utils.py
Contribution by [LM Studio](https://lmstudio.ai/) Team. Initial implementation, more details to follow. Please note numerical precision considerations vs. the reference implementation.
=> Add gpt_oss model

mlx_lm/convert.py, mlx_lm/evaluate.py, mlx_lm/models/hunyuan_v1_dense.py, mlx_lm/tuner/utils.py, tests/test_models.py
This closes #350 
Hunyuan_v1_dense have 2 different model architectures
- 0.5B and 4B
- 1.8B and 7B
=> Hunyuan V1 Dense model support

mlx_lm/quant/dwq.py
Reverting for now as it's not doing anything.
I'll test out the `jsm_div_loss` and a proper symmetric KL and report back.
=> Revert symmetric kl

mlx_lm/evaluate.py
Fixes #366 . 
I distinctly remember Alex Barron fixing this some time ago but looking at the code it was quite wrong with multiple nodes due to the grouping of prompts 🤷‍♂️. Regardless, it is now correct and we are getting exactly the same results for 1, 2, 3, 4, 5 nodes.
=> Fix distributed evaluate

mlx_lm/generate.py, tests/test_generate.py
On M4 Max:
Prompt length 2048:
Model | Pre Tok/Sec | Post Tok/sec
--- | ---- | -----
Gemma3 270M | 17690.713  | 28079.604
Qwen3 0.6B Q4 | 8452.687 | 10278.775
Qwen3 30B A3B Q4 | 1593.237 | 1731.991
GPT OSS 20B Q4 | 1344.136 | 1588.662
Prompt length 512
Model | Pre Tok/Sec | Post Tok/sec
--- | ---- | -----
Gemma3 270M | 18179.581 | 24566.622
Qwen3 0.6B Q4 |  8785.682 | 9520.375
Qwen3 30B A3B Q4 | 1415.606 | 1480.329
GPT OSS 20B Q4 | 1302.705 | 1543.574
=> only apply lm_head to the last token

mlx_lm/__main__.py, mlx_lm/_version.py, mlx_lm/benchmark.py, mlx_lm/convert.py, mlx_lm/generate.py, mlx_lm/models/gpt_oss.py, mlx_lm/models/qwen2_vl.py, mlx_lm/models/rope_utils.py, mlx_lm/models/switch_layers.py, mlx_lm/perplexity.py, mlx_lm/quant/dwq.py, mlx_lm/quant/dynamic_quant.py, mlx_lm/server.py, mlx_lm/utils.py, requirements.txt, setup.py, tests/test_generate.py
Requires https://github.com/ml-explore/mlx/pull/2499
gpt-oss runs and is pretty fast on an M2 Ultra. The model is a hybrid quant, 8-bit for the bf16 layers and mxfp4 for the pre-quantized MoE blocks. One can push the speed up to 126 tok/sec by doing all of it in 4-bit.
Convert with e.g.:
```
mlx_lm.convert --hf-path openai/gpt-oss-20b -q --q-bits 8
```
Run with:
```
mlx_lm.generate --model mlx_model --prompt "Write a story about Einstein" -m 512
==========
<|channel|>analysis<|message|>The user wants a story about Einstein. We need to write a story. The user didn't specify length or style. We can choose a creative narrative, perhaps a fictionalized account of Einstein's life, or a story that includes Einstein as a character. We can incorporate his scientific achievements, his personality, …
```
=> support mxfp4

mlx_lm/models/hunyuan_v1_dense.py
Remove lm head if weights are tied.
```
mlx_lm.convert \
--hf-path tencent/Hunyuan-MT-Chimera-7B \
-q
```
=> Fix hunyuan v1 dense

mlx_lm/models/mamba.py
removed the custom DepthWiseConv1d class and used the build in conv1d with the groups param, makes it easier and has a small speed improvement.
=> remove manual conv class in mamba1

ACKNOWLEDGMENTS.md, mlx_lm/models/lille-130m.py, mlx_lm/tuner/utils.py, tests/test_models.py
python -m mlx_lm.generate --model Desktop/lille --prompt "who is michael jackson"
==========
As of my last update in April 2023, Michael Jackson is a former American actor, born on February 12, 2013, and died on February 20, 2021. He was born and passed away on February 20, 2021. He was known for his work in the entertainment industry, particularly his roles in movies, television shows, and his work in the entertainment industry. He has been involved in various other roles, including acting, and has been involved in various other roles. He has been known
==========
Prompt: 10 tokens, 89.930 tokens-per-sec
Generation: 100 tokens, 331.787 tokens-per-sec
Peak memory: 0.546 GB
---
python -m mlx_lm.lora \
--train \
--model Desktop/lille \
--data mlx-community/wikisql \
--fine-tune-type lora \ …
=> Add lille 130m

ACKNOWLEDGMENTS.md, mlx_lm/models/glm.py, mlx_lm/tuner/utils.py, tests/test_models.py
=> Adding GLM

README.md, mlx_lm/__init__.py, mlx_lm/benchmark.py, mlx_lm/evaluate.py, mlx_lm/examples/batch_generate_response.py, mlx_lm/generate.py, mlx_lm/models/base.py, mlx_lm/models/cache.py, tests/test_evaluate.py, tests/test_generate.py, tests/test_models.py, tests/test_prompt_cache.py
There is a lot going on here.. the basics for batch generation are mostly here but it needs some tuning / refinement for perf.
The main thing to review here the APIs that are introduced. There are a few note-able ones:
```
mlx_lm.evaluate --model Qwen/Qwen3-4B-Instruct-2507 --task mmlu_pro --limit 20 --max-tokens 2048
```
Edit: results are close (larger eval in progress):
Single:     "exact_match,custom-extract": 0.6392857142857142,
Batch:     "exact_match,custom-extract": 0.6535714285714286,
Batch is about 5x faster:
Single: 53:06.68 total
Batch: 11:47.11 total
A high level API for generating completions for a bunch of prompts:
```python
texts, stats = batch_generate(model, tokenizer, prompts)
```
Q: maybe `batch_generate` should return a dictionary or a data class to make it easier to …
=> Batch generation

mlx_lm/evaluate.py
=> fix: handle cache offset safely for mamba error

mlx_lm/quant/dynamic_quant.py, mlx_lm/utils.py
=> Fix quant predicate

mlx_lm/benchmark.py, mlx_lm/models/gated_delta.py, mlx_lm/models/qwen3_next.py, tests/test_models.py
Non batched:
```
mlx_lm.benchmark --model mlx-community/Qwen3-Next-80B-A3B-Thinking-4bit -p 128 -g 128  
Averages: prompt_tps=469.910, generation_tps=65.284, peak_memory=45.090
```
Batched:
```
mlx_lm.benchmark --model mlx-community/Qwen3-Next-80B-A3B-Thinking-4bit -p 128 -g 128 -b 16
Averages: prompt_tps=944.421, generation_tps=301.916, peak_memory=46.885
```
=> qwen3 next batching

mlx_lm/models/cache.py, tests/test_prompt_cache.py
=> Fix RotatingKVCache update

mlx_lm/_version.py, mlx_lm/models/llama.py, tests/test_models.py
=> Add Code World Model support

mlx_lm/models/bailing_moe.py
Fix for `inclusionAI/Ring-1T-preview`
=> fix bailing moe

mlx_lm/utils.py
Closes #517 
Model is pretty verbose, issue ackowledged by creators. Issue even bigger with 4-bit quantization, 5-bit+ works pretty well.
Strong model with MIT license.
=> Add Apriel 1.5

mlx_lm/tuner/lora.py
=> Fix lora MoEs
